import { Book } from "../models/book.interface";

export const booksContent: Book[] = [
  {
    title: "Sum",
    author: "David Eagleman",
    yearRead: 2022,
    rating: 5,
    comment: "I could not recommend this book more.",
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    yearRead: 2021,
    rating: 5,
    comment: "The best book about habits there is.",
  },
  {
    title: "Humanity",
    author: "Jonathan Glover",
    yearRead: 2020,
    rating: 5,
    comment: "Insights from our cruelest atrocities.",
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    yearRead: 2019,
    rating: 5,
    comment: "History for everyone.",
  },
  {
    title: "The Manual",
    author: "Epictetus and Sam Torode",
    yearRead: 2022,
    rating: 5,
    comment: "Stoicism stoicly explained.",
  },
  {
    title: "Start with Why",
    author: "Simon Sinek",
    yearRead: 2018,
    rating: 5,
    comment: "Make your sales pitch inspiring.",
  },
  {
    title: "Crucial Conversations",
    author: "Al Switzler",
    yearRead: 2018,
    rating: 4,
    comment: "Lead difficult conversations gracefully.",
  },
  {
    title: "You are not listening",
    author: "Kate Murphy",
    yearRead: 2020,
    rating: 4,
    comment: "Great examples on how to listen better.",
  },
  {
    title: "Bloodchild",
    author: "Octavia E. Butler",
    yearRead: 2021,
    rating: 4,
    comment: "My favorite fiction book.",
  },

  {
    title: "Man's Search for Meaning",
    author: "Viktor Frankl",
    yearRead: 2022,
    rating: 4,
    comment: "Research under the toughest conditions.",
  },
  {
    title: "The six pillars of self-steem",
    author: "Nathaniel Branden",
    yearRead: 2021,
    rating: 4,
    comment: "Very thorough analysis on self-esteem.",
  },
  {
    title: "Thinking fast and slow",
    author: "Daniel Kahneman",
    yearRead: 2018,
    rating: 4,
    comment: "Deep insights into how we think",
  },
  {
    title: "The Rational Optimist",
    author: "Matt Ridley",
    yearRead: 2021,
    rating: 4,
    comment: "An optimistic view into the future.",
  },
  {
    title: "Los Cuatro Acuerdos",
    author: "Don Miguel Ruiz",
    yearRead: 2018,
    rating: 4,
    comment: "Practical knowledge simplified.",
  },
  {
    title: "Leaders Eat Last",
    author: "Simon Sinek",
    yearRead: 2018,
    rating: 4,
    comment: "",
  },
  {
    title: "Meditations",
    author: "Marcus Aurelius",
    yearRead: 2022,
    rating: 4,
  },
  {
    title: "Make",
    author: "Pieter Levels",
    yearRead: 2021,
    rating: 4,
  },
  {
    title: "Managing Oneself",
    author: "Peter Drucker",
    yearRead: 2018,
    rating: 3,
    comment: "",
  },
  {
    title: "Designer Relationships",
    author: "Mark A. Michaels and Patricia Johnson",
    yearRead: 2021,
    rating: 3,
    comment: "",
  },
  {
    title: "Polysecure",
    author: "Jessica Fern",
    yearRead: 2021,
    rating: 3,
  },
  {
    title: "The Gentleman's Guide to Vice and Virtue",
    author: "Mackenzi Lee",
    yearRead: 2022,
    rating: 3,
    comment: "",
  },
  {
    title: "The Power of Habit",
    author: "Charles Duhigg",
    yearRead: 2018,
    rating: 3,
    comment: "",
  },
  {
    title: "The leader who had no tittle",
    author: "Robin Sharma",
    yearRead: 2019,
    rating: 3,
    comment: "",
  },
  {
    title: "Sprint",
    author: "Jake Knapp",
    yearRead: 2019,
    rating: 3,
    comment: "",
  },
  {
    title: "The subtle art of not giving a fuck",
    author: "Mark Manson",
    yearRead: 2020,
    rating: 3,
    comment: "",
  },
  {
    title: "Sex at dawn",
    author: "Christopher Ryan",
    yearRead: 2020,
    rating: 3,
  },
  {
    title: "12 Rules for Life",
    author: "Jordan Peterson",
    yearRead: 2021,
    rating: 3,
  },
  {
    title: "Rework",
    author: "Jason Fried",
    yearRead: 2020,
    rating: 3,
    comment: "",
  },
  {
    title: "The way of the Superior Man",
    author: "David Deida",
    yearRead: 2018,
    rating: 2,
    comment: "",
  },
  {
    title: "Exactly What to Say",
    author: "Phil Jones",
    yearRead: 2018,
    rating: 2,
    comment: "",
  },
  {
    title: "Outwitting the Devil",
    author: "Napoleon Hill",
    yearRead: 2018,
    rating: 2,
    comment: "",
  },

  {
    title: "If I Understood You, Would I Have This Look on My Face?",
    author: "Alan Alda",
    yearRead: 2021,
    rating: 2,
    comment: "",
  },
  {
    title: "La ridícula idea de no volver a verte",
    author: "Rosa Montero",
    yearRead: 2022,
    rating: 2,
    comment: "",
  },
  {
    title: "Tropic of Cancer",
    author: "Henry Miller",
    yearRead: 2022,
    rating: 2,
    comment: "",
  },
  {
    title: "The Love Secret",
    author: "Sue Johnson",
    yearRead: 2021,
    rating: 1,
    comment: "",
  },

  {
    title: "Talking to Robots",
    author: "David Ewing Duncan",
    yearRead: 2019,
    rating: 1,
    comment: "",
  },
];
