import { Book } from "../models/book.interface";

export const booksContent: Book[] = [
  {
    title: "Sum",
    author: "David Eagleman",
    yearRead: 2022,
    rating: 5,
    comment: "I could not recommend this book more.",
    isbn: "9780307377340",
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    yearRead: 2021,
    rating: 5,
    comment: "The best book about habits there is.",
    isbn: "1847941842",
  },
  {
    title: "How to Win Friends & Influence People",
    author: "Dale Carnegie",
    yearRead: 2017,
    rating: 5,
    comment: "My favorite book about communication.",
    imgUrl: "https://m.media-amazon.com/images/I/71vK0WVQ4rL.jpg",
  },
  {
    title: "Humanity",
    author: "Jonathan Glover",
    yearRead: 2020,
    rating: 5,
    comment: "Insights from our cruelest atrocities.",
    isbn: "0300186401",
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    yearRead: 2019,
    rating: 5,
    comment: "History for everyone.",
    isbn: "0062316117",
  },
  {
    title: "The Manual",
    author: "Epictetus and Sam Torode",
    yearRead: 2022,
    rating: 5,
    comment: "Stoicism stoicly explained.",
    isbn: "1545461112",
  },
  {
    title: "Start with Why",
    author: "Simon Sinek",
    yearRead: 2018,
    rating: 5,
    comment: "Make your sales pitch inspiring.",
    isbn: "9780241958223",
  },
  {
    title: "Crucial Conversations",
    author: "Al Switzler",
    yearRead: 2018,
    rating: 4,
    comment: "Lead difficult conversations gracefully.",
    isbn: "9780071401944",
  },
  {
    title: "You are not listening",
    author: "Kate Murphy",
    yearRead: 2020,
    rating: 4,
    comment: "Great examples on how to listen better.",
    isbn: "9781250297198",
  },
  {
    title: "Bloodchild",
    author: "Octavia E. Butler",
    yearRead: 2021,
    rating: 4,
    comment: "My favorite fiction book.",
    isbn: "1583226982",
  },
  {
    title: "Man's Search for Meaning",
    author: "Viktor Frankl",
    yearRead: 2022,
    rating: 4,
    comment: "Research under the toughest conditions.",
    isbn: "0807014273",
  },
  {
    title: "The six pillars of self-steem",
    author: "Nathaniel Branden",
    yearRead: 2021,
    rating: 4,
    comment: "Very thorough analysis on self-esteem.",
    isbn: "0553374397",
  },
  {
    title: "Thinking fast and slow",
    author: "Daniel Kahneman",
    yearRead: 2018,
    rating: 4,
    comment: "Deep insights into how we think",
    isbn: "9780141033570",
  },
  {
    title: "The Rational Optimist",
    author: "Matt Ridley",
    yearRead: 2021,
    rating: 4,
    comment: "An optimistic view into the future.",
    isbn: "9780007267118",
  },
  {
    title: "Los Cuatro Acuerdos",
    author: "Don Miguel Ruiz",
    yearRead: 2018,
    rating: 4,
    comment: "Practical knowledge simplified.",
    isbn: "9781878424938",
  },
  {
    title: "Leaders Eat Last",
    author: "Simon Sinek",
    yearRead: 2018,
    rating: 4,
    comment: "",
    isbn: "9780670923175",
  },
  {
    title: "Meditations",
    author: "Marcus Aurelius",
    yearRead: 2022,
    rating: 4,
    imgUrl: "https://i.ebayimg.com/images/g/HggAAOSwimBjL4BI/s-l1600.jpg",
  },
  {
    title: "Make",
    author: "Pieter Levels",
    yearRead: 2021,
    rating: 4,
    imgUrl: "https://readmake.com/media-book-small.jpg",
  },
  {
    title: "Managing Oneself",
    author: "Peter Drucker",
    yearRead: 2018,
    rating: 3,
    comment: "",
    isbn: "9781422123126",
  },
  {
    title: "Designer Relationships",
    author: "Mark A. Michaels and Patricia Johnson",
    yearRead: 2021,
    rating: 3,
    comment: "",
    isbn: "9781627781473",
  },
  {
    title: "Polysecure",
    author: "Jessica Fern",
    yearRead: 2021,
    rating: 3,
    imgUrl:
      "https://images.thalia.media/07/-/92885d86a7474687a7998d7b72ca95da/polysecure-taschenbuch-jessica-fern-englisch.jpeg",
  },
  {
    title: "The Gentleman's Guide to Vice and Virtue",
    author: "Mackenzi Lee",
    yearRead: 2022,
    rating: 3,
    comment: "",
    isbn: "9780062382801",
  },
  {
    title: "The Power of Habit",
    author: "Charles Duhigg",
    yearRead: 2018,
    rating: 3,
    comment: "",
    isbn: "9780812981605",
  },
  {
    title: "The leader who had no tittle",
    author: "Robin Sharma",
    yearRead: 2019,
    rating: 3,
    comment: "",
    isbn: "9781439109120",
  },
  {
    title: "Sprint",
    author: "Jake Knapp",
    yearRead: 2019,
    rating: 3,
    comment: "",
    isbn: "9780593076118",
  },
  {
    title: "The subtle art of not giving a fuck",
    author: "Mark Manson",
    yearRead: 2020,
    rating: 3,
    comment: "",
    isbn: "9780062641540",
  },
  {
    title: "Sex at dawn",
    author: "Christopher Ryan",
    yearRead: 2020,
    rating: 3,
    isbn: "9780061707803",
  },
  {
    title: "12 Rules for Life",
    author: "Jordan Peterson",
    yearRead: 2021,
    rating: 3,
    isbn: "9780345816023",
  },
  {
    title: "Rework",
    author: "Jason Fried",
    yearRead: 2020,
    rating: 3,
    comment: "",
    isbn: "9780307463746",
  },
  {
    title: "The way of the Superior Man",
    author: "David Deida",
    yearRead: 2018,
    rating: 2,
    comment: "",
    isbn: "1889762105",
  },
  {
    title: "Exactly What to Say",
    author: "Phil Jones",
    yearRead: 2018,
    rating: 2,
    comment: "",
    imgUrl: "https://m.media-amazon.com/images/I/51uZii1hhnL.jpg",
  },
  {
    title: "Outwitting the Devil",
    author: "Napoleon Hill",
    yearRead: 2018,
    rating: 2,
    comment: "",
    isbn: "9781402784538",
  },

  {
    title: "If I Understood You, Would I Have This Look on My Face?",
    author: "Alan Alda",
    yearRead: 2021,
    rating: 2,
    comment: "",
    isbn: "1524781665",
  },
  {
    title: "La ridícula idea de no volver a verte",
    author: "Rosa Montero",
    yearRead: 2022,
    rating: 2,
    comment: "",
    isbn: "9789584235701",
  },
  {
    title: "Tropic of Cancer",
    author: "Henry Miller",
    yearRead: 2022,
    rating: 2,
    comment: "",
    imgUrl: "https://m.media-amazon.com/images/I/41PEqpOEB1L.jpg",
  },
  {
    title: "The Love Secret",
    author: "Sue Johnson",
    yearRead: 2021,
    rating: 1,
    comment: "",
    isbn: "9780749955533",
  },
  {
    title: "Talking to Robots",
    author: "David Ewing Duncan",
    yearRead: 2019,
    rating: 1,
    comment: "",
    imgUrl: "https://m.media-amazon.com/images/I/41WjbGvYdSL._AC_SY780_.jpg",
  },
];
