import { Book } from "../models/book.interface";

export const booksContent: Book[] = [
  {
    title: "Sum",
    author: "David Eagleman",
    yearRead: 2022,
    rating: 5,
    comment: "I could not recommend this book more.",
    isbn: "9780307377340",
    link: "https://www.goodreads.com/book/show/4948826-sum",
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    yearRead: 2021,
    rating: 5,
    comment: "The best book about habits there is.",
    isbn: "1847941842",
    link: "https://www.goodreads.com/book/show/40121378-atomic-habits?ref=nav_sb_ss_1_13",
  },
  {
    title: "How to Win Friends & Influence People",
    author: "Dale Carnegie",
    yearRead: 2017,
    rating: 5,
    comment: "My favorite book about communication.",
    imgUrl: "https://m.media-amazon.com/images/I/71vK0WVQ4rL.jpg",
    link: "https://www.goodreads.com/book/show/4865.How_to_Win_Friends_and_Influence_People?ref=nav_sb_ss_1_37",
  },
  {
    title: "Humanity",
    author: "Jonathan Glover",
    yearRead: 2020,
    rating: 5,
    comment: "Insights from our cruelest atrocities.",
    isbn: "0300186401",
    link: "https://www.goodreads.com/book/show/321263.Humanity?ac=1&from_search=true&qid=Z1k0O8hIoD&rank=1",
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    yearRead: 2019,
    rating: 5,
    comment: "History for everyone.",
    isbn: "0062316117",
    link: "https://www.goodreads.com/book/show/23692271-sapiens?ref=nav_sb_ss_1_5",
  },
  {
    title: "The Manual",
    author: "Epictetus and Sam Torode",
    yearRead: 2022,
    rating: 5,
    comment: "Stoicism stoicly explained.",
    isbn: "1545461112",
    link: "https://www.goodreads.com/book/show/34946912-the-manual?ref=nav_sb_ss_2_15",
  },
  {
    title: "Start with Why",
    author: "Simon Sinek",
    yearRead: 2018,
    rating: 5,
    comment: "Make your sales pitch inspiring.",
    isbn: "9780241958223",
    link: "https://www.goodreads.com/book/show/7108725-start-with-why?ref=nav_sb_ss_1_14",
  },
  {
    title: "Crucial Conversations",
    author: "Al Switzler",
    yearRead: 2018,
    rating: 4,
    comment: "Lead difficult conversations gracefully.",
    isbn: "9780071401944",
    link: "https://www.goodreads.com/book/show/15014.Crucial_Conversations?from_search=true&from_srp=true&qid=lbv9e2m2Ag&rank=1",
  },
  {
    title: "the 7 habits of highly effective teens",
    author: "Sean Covey",
    yearRead: 2009,
    rating: 4,
    comment: "The first book I read on productivity.",
    imgUrl: "https://m.media-amazon.com/images/I/A1sxoppX3JL.jpg",
    link: "https://www.goodreads.com/book/show/783127.The_7_Habits_Of_Highly_Effective_Teens",
  },
  {
    title: "You're not listening",
    author: "Kate Murphy",
    yearRead: 2020,
    rating: 4,
    comment: "Great examples on how to listen better.",
    isbn: "9781250297198",
    link: "https://www.goodreads.com/book/show/45892276-you-re-not-listening",
  },
  {
    title: "Bloodchild and other stories",
    author: "Octavia E. Butler",
    yearRead: 2021,
    rating: 4,
    comment: "My favorite fiction book.",
    isbn: "1583226982",
    link: "https://www.goodreads.com/book/show/60930.Bloodchild_and_Other_Stories?ref=nav_sb_ss_1_10",
  },
  {
    title: "Man's Search for Meaning",
    author: "Viktor Frankl",
    yearRead: 2022,
    rating: 4,
    comment: "Research under the toughest conditions.",
    isbn: "0807014273",
    link: "https://www.goodreads.com/book/show/4069.Man_s_Search_for_Meaning?ref=nav_sb_ss_1_24",
  },
  {
    title: "The six pillars of self-steem",
    author: "Nathaniel Branden",
    yearRead: 2021,
    rating: 4,
    comment: "Very thorough analysis on self-esteem.",
    isbn: "0553374397",
    link: "https://www.goodreads.com/book/show/18808930-the-six-pillars-of-self-esteem?ref=nav_sb_ss_1_29",
  },
  {
    title: "Thinking, fast and slow",
    author: "Daniel Kahneman",
    yearRead: 2018,
    rating: 4,
    comment: "Deep insights into how we think",
    isbn: "9780141033570",
    link: "https://www.goodreads.com/book/show/11468377-thinking-fast-and-slow?ref=nav_sb_ss_1_22",
  },
  {
    title: "The Rational Optimist",
    author: "Matt Ridley",
    yearRead: 2021,
    rating: 4,
    comment: "An optimistic view into the future.",
    isbn: "9780007267118",
    link: "https://www.goodreads.com/book/show/7776209-the-rational-optimist?ref=nav_sb_ss_1_21",
  },
  {
    title: "Los Cuatro Acuerdos",
    author: "Don Miguel Ruiz",
    yearRead: 2018,
    rating: 4,
    comment: "Practical knowledge simplified.",
    isbn: "9781878424938",
    link: "https://www.goodreads.com/book/show/6600.Los_cuatro_acuerdos?ref=nav_sb_ss_1_19",
  },
  {
    title: "Leaders Eat Last",
    author: "Simon Sinek",
    yearRead: 2018,
    rating: 4,
    comment: "",
    isbn: "9780670923175",
    link: "https://www.goodreads.com/book/show/16144853-leaders-eat-last?ref=nav_sb_ss_1_16",
  },
  {
    title: "Meditations",
    author: "Marcus Aurelius",
    yearRead: 2022,
    rating: 4,
    imgUrl: "https://i.ebayimg.com/images/g/HggAAOSwimBjL4BI/s-l1600.jpg",
    link: "https://www.goodreads.com/book/show/30659.Meditations?ref=nav_sb_ss_1_11",
  },
  {
    title: "Make",
    author: "Pieter Levels",
    yearRead: 2021,
    rating: 4,
    imgUrl: "https://readmake.com/media-book-small.jpg",
    link: "https://www.goodreads.com/book/show/41570135-make?ref=nav_sb_ss_1_16",
  },
  {
    title: "Managing Oneself",
    author: "Peter Drucker",
    yearRead: 2018,
    rating: 3,
    comment: "",
    isbn: "9781422123126",
    link: "https://www.goodreads.com/book/show/2477223.Managing_Oneself?ref=nav_sb_ss_1_16",
  },
  {
    title: "Designer Relationships",
    author: "Mark A. Michaels and Patricia Johnson",
    yearRead: 2021,
    rating: 3,
    comment: "",
    isbn: "9781627781473",
    link: "https://www.goodreads.com/book/show/24402980-designer-relationships?ref=nav_sb_ss_1_22",
  },
  {
    title: "Polysecure",
    author: "Jessica Fern",
    yearRead: 2021,
    rating: 3,
    imgUrl:
      "https://images.thalia.media/07/-/92885d86a7474687a7998d7b72ca95da/polysecure-taschenbuch-jessica-fern-englisch.jpeg",
    link: "https://www.goodreads.com/book/show/52569124-polysecure?ref=nav_sb_ss_1_10",
  },
  {
    title: "The Gentleman's Guide to Vice and Virtue",
    author: "Mackenzi Lee",
    yearRead: 2022,
    rating: 3,
    comment: "",
    isbn: "9780062382801",
    link: "https://www.goodreads.com/book/show/29283884-the-gentleman-s-guide-to-vice-and-virtue?ref=nav_sb_ss_1_40",
  },
  {
    title: "The Power of Habit",
    author: "Charles Duhigg",
    yearRead: 2018,
    rating: 3,
    comment: "",
    isbn: "9780812981605",
    link: "https://www.goodreads.com/book/show/12609433-the-power-of-habit?ref=nav_sb_ss_1_18",
  },
  {
    title: "The leader who had no tittle",
    author: "Robin Sharma",
    yearRead: 2019,
    rating: 3,
    comment: "",
    isbn: "9781439109120",
    link: "https://www.goodreads.com/book/show/6881578-the-leader-who-had-no-title?ref=nav_sb_ss_1_28",
  },
  {
    title: "Sprint",
    author: "Jake Knapp",
    yearRead: 2019,
    rating: 3,
    comment: "",
    isbn: "9780593076118",
    link: "https://www.goodreads.com/book/show/25814544-sprint?ref=nav_sb_ss_1_6",
  },
  {
    title: "The subtle art of not giving a fuck",
    author: "Mark Manson",
    yearRead: 2020,
    rating: 3,
    comment: "",
    isbn: "9780062641540",
    link: "https://www.goodreads.com/book/show/28257707-the-subtle-art-of-not-giving-a-f-ck?ref=nav_sb_ss_1_7",
  },
  {
    title: "Sex at dawn",
    author: "Christopher Ryan",
    yearRead: 2020,
    rating: 3,
    isbn: "9780061707803",
    link: "https://www.goodreads.com/book/show/7640261-sex-at-dawn?ref=nav_sb_ss_1_11",
  },
  {
    title: "12 Rules for Life",
    author: "Jordan Peterson",
    yearRead: 2021,
    rating: 3,
    isbn: "9780345816023",
    link: "https://www.goodreads.com/book/show/30257963-12-rules-for-life?ref=nav_sb_ss_1_17",
  },
  {
    title: "Rework",
    author: "Jason Fried",
    yearRead: 2020,
    rating: 3,
    comment: "",
    isbn: "9780307463746",
    link: "https://www.goodreads.com/book/show/6732019-rework?ref=nav_sb_ss_1_6",
  },
  {
    title: "rich dad poor dad",
    author: "Robert T. Kiyosaki, Sharon L. Lechter",
    yearRead: 2012,
    rating: 3,
    comment: "",
    imgUrl: "https://m.media-amazon.com/images/I/51u8ZRDCVoL._SX330_BO1,204,203,200_.jpg",
    link: "https://www.goodreads.com/book/show/69571.Rich_Dad_Poor_Dad",
  },
  {
    title: "The way of the Superior Man",
    author: "David Deida",
    yearRead: 2018,
    rating: 2,
    comment: "",
    isbn: "1889762105",
    link: "https://www.goodreads.com/book/show/79424.The_Way_of_the_Superior_Man?ref=nav_sb_ss_1_27",
  },
  {
    title: "Exactly What to Say",
    author: "Phil Jones",
    yearRead: 2018,
    rating: 2,
    comment: "",
    imgUrl: "https://m.media-amazon.com/images/I/51uZii1hhnL.jpg",
    link: "https://www.goodreads.com/book/show/35414701-exactly-what-to-say?ref=nav_sb_ss_1_19",
  },
  {
    title: "Outwitting the Devil",
    author: "Napoleon Hill",
    yearRead: 2018,
    rating: 2,
    comment: "",
    isbn: "9781402784538",
    link: "https://www.goodreads.com/book/show/35414701-exactly-what-to-say?ref=nav_sb_ss_1_19",
  },
  {
    title: "If I Understood You, Would I Have This Look on My Face?",
    author: "Alan Alda",
    yearRead: 2021,
    rating: 2,
    comment: "",
    isbn: "1524781665",
    link: "https://www.goodreads.com/book/show/40600256-if-i-understood-you-would-i-have-this-look-on-my-face?ref=nav_sb_ss_1_55",
  },
  {
    title: "La ridícula idea de no volver a verte",
    author: "Rosa Montero",
    yearRead: 2022,
    rating: 2,
    comment: "",
    isbn: "9789584235701",
    link: "https://www.goodreads.com/book/show/17567272-la-rid-cula-idea-de-no-volver-a-verte?ref=nav_sb_ss_1_37",
  },
  {
    title: "Tropic of Cancer",
    author: "Henry Miller",
    yearRead: 2022,
    rating: 2,
    comment: "",
    imgUrl: "https://m.media-amazon.com/images/I/41PEqpOEB1L.jpg",
    link: "https://www.goodreads.com/book/show/249.Tropic_of_Cancer?ref=nav_sb_ss_1_16",
  },
  {
    title: "The Love Secret",
    author: "Sue Johnson",
    yearRead: 2021,
    rating: 1,
    comment: "",
    isbn: "9780749955533",
    link: "https://www.goodreads.com/book/show/20706519-the-love-secret?ref=nav_sb_ss_2_20",
  },
  {
    title: "Talking to Robots",
    author: "David Ewing Duncan",
    yearRead: 2019,
    rating: 1,
    comment: "",
    imgUrl: "https://m.media-amazon.com/images/I/41WjbGvYdSL._AC_SY780_.jpg",
    link: "https://www.goodreads.com/book/show/42835232-talking-to-robots?ref=nav_sb_ss_1_17",
  },
];
